version: "3.8"

services:
  api:
    build:
      context: ./docker/
      dockerfile: flask.dockerfile
      args:
        PROJECT_DIR: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    ports:
      - "5000:5000"
    command: "python3 app.py"
    environment: 
      - SAMPLE_API_TOKEN=44KI44GP44GC44KL44Go44O844GP44KT
